### PR TITLE
mdx_test: Lazily initialize OCaml toplevel

### PR DESCRIPTION
**Pull request by bcc32**
This changes the OCaml toplevel to be a lazy value, which is only
forced when needed to run tests in an OCaml block.

The motivation behind this change is to avoid stderr output from the
init process (e.g., errors while registering pretty-printers) spilling
into the test executable's output, which can trip up some build tools.

### CODE REVIEW

**Comment by samoht** [comment]
Do you mind rebasing this?

**Comment by bcc32** [comment]
Done, thanks for the ping.

**Comment by samoht** [comment]
Thanks! Do you think it would be possible to add a test case for this?

**Comment by samoht** [comment]
Also: could you add a change entry? Many thanks!

**Comment by bcc32** [comment]
In trying to come up with a good test, I realized that the original bug we observed was caused by a separate internal Jane Street patch to mdx (for our custom toplevel backend) and could not be reproduced in this repo.  I have gone through and refactored the fix to be more specifically tailored for our internal toplevel backend and I think this can be dropped.

Thank you for taking a look at this PR!

**Pull request closed without merging**
