### PR TITLE
Simplify --syntax test cases so that they don't randomly fail

### PR DESCRIPTION
**Pull request by NathanReb**
This test case randomly fails quite often in the CI or locally. I'm not sure why since I can't reproduce it but I'm willing to try anything to fix it and that's a start!

### CODE REVIEW

**Comment by NathanReb** [comment]
Interesting https://ci.ocamllabs.io/github/realworldocaml/mdx/commit/9f816042b37ab166388aee2c4c7135e6c6e351e0/variant/4.06.

**Comment by NathanReb** [comment]
I removed the newline, it's not what's being tested here anyway

**Comment by NathanReb** [comment]
Ok after giving a better look at the test case it doesn't need to do such things at all so let's just replace the shell block by a simple echo!

**Comment by NathanReb** [comment]
I'm still a bit puzzled as to why they weren't working though

**Comment by Julow** [comment]
I fail to reproduce.

**Comment by NathanReb** [comment]
Can we agree that the test case can be simplified to this and merge?

**Comment by Julow** [comment]
I don't think we should have merged this. This was testing that Mdx supports multiline commands with cram syntax and pass them to the shell as we would expect.
The heredoc is an important and tricky use case.

**Comment by NathanReb** [comment]
No, this was not the point of that specific test. The point of the test was to ensure that the `--syntax` option was working correctly.

See https://github.com/realworldocaml/mdx/commit/56dcec39ebb00b5f9de7d31c96f1791be27b68a1#diff-b2ba33c462caee5b3eedec8cd7315ff6.

**Comment by Julow** [comment]
True, there is an other test for heredocs.

**Pull request merged**
