### PR TITLE
Remove output subcommand

### PR DESCRIPTION
**Pull request by NathanReb**
This removes the `ocaml-mdx output` subcommand since it has now been moved to https://github.com/realworldocaml/book.

It shouldn't be an issue as RWO is the only user of this command!

### CODE REVIEW

**Comment by samoht** [comment]
Looks good but can you also remove https://github.com/realworldocaml/mdx/blob/master/mdx.opam#L30 so that the pass could pass?

**Comment by samoht** [comment]
> Is there a replacement in RWO yet ?

Yes, it's here: https://github.com/realworldocaml/book/blob/master/bin/bin/convert_md.ml

**Comment by NathanReb** [comment]
> Looks good but can you also remove https://github.com/realworldocaml/mdx/blob/master/mdx.opam#L30 so that the tests could pass?

Good catch! I'll remove that

**Comment by NathanReb** [comment]
Both CI are green! Let's merge!

**Pull request merged**
