### PR TITLE
Handle no such file exception

### LINKED ISSUE #288: Calling test commad on non-existing file results in uncaught internal error
Reproduction:

```
ocaml-mdx test fake-file
ocaml-mdx-test: internal error, uncaught exception:
                Sys_error("fake-file: No such file or directory")
```

The error is easy to understand, but just for the sake of polish, it would probably be a good idea to catch this kind of common case and provider user-friendly feedback.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #288

### CODE REVIEW

**Review by Julow — COMMENTED** [review]
There is an other way to implement this, Cmdliner has a `file` conv that tests if the file exist. This way, we'll have the same error message as other tools using cmdliner:
```
  Arg.(... & pos 0 (some file) None & ...)
```
This has the added advantage that the `file` arg is shared between all commands.

**Comment by Julow** [comment]
There is also `non_dir_file` that also checks that it's not a directory.

**Comment by gpetiot** [comment]
> There is also `non_dir_file` that also checks that it's not a directory.

It's better indeed, thanks!

**Review by Julow — APPROVED** [review]
This can be done for `prelude` (`non_dir_file`) and `root` (`dir`) too, as we are at it.
Otherwise, looks good to me.

**Pull request merged**
